export const USER_INFO           =  'USER_INFO'
export const MEMBER_INFO         =  'MEMBER_INFO'
export const CLEAR_USER_INFO     =  'CLEAR_USER_INFO'
export const CLEAR_MEMBER_INFO   =  'CLEAR_MEMBER_INFO'
export const IMAGE_INFO          =  'IMAGE_INFO'